trigger:
  - main

resources:
  - repo: self

variables:
  imageName: "ghcr.io/dickymuliafiqri/binocular:main"

stages:
  - stage: Build
    displayName: Build image
    jobs:
      - job: BuildAndPush
        displayName: Build and Push Docker Image
        pool:
          vmImage: ubuntu-latest
        steps:
          - bash: docker login ghcr.io -u dickymuliafiqri -p $(DOCKER_PASS)
            displayName: Login to docker container
          - bash: docker build -t $(imageName) .
            displayName: Build docker image
          - bash: docker push $(imageName)
            displayName: Push docker image to container
